/** One catalog, served by both repository implementations in the contract suite. */
export const CATALOG = [
  {
    id: "office.desk.pod4",
    name: "Four-person desk pod",
    category: "furniture",
    subcategory: "desk",
    tags: ["desk", "pod", "workstation"],
    style: "modern",
    tileSize: 32,
    dimensions: { width: 4, height: 3 },
    placement: "floor",
    tilesetId: "office-core",
    tileId: 42,
    collision: { blocking: true },
    interaction: { class: "workstation", capacity: 4 },
    version: "3",
  },
  {
    id: "office.chair.swivel",
    name: "Swivel chair",
    category: "furniture",
    subcategory: "chair",
    tags: ["chair", "seat"],
    style: "modern",
    tileSize: 32,
    dimensions: { width: 1, height: 1 },
    placement: "floor",
    tilesetId: "office-core",
    tileId: 7,
    collision: { blocking: false },
  },
  {
    id: "decor.plant.fiddle",
    name: "Fiddle-leaf fig",
    category: "decoration",
    tags: ["plant", "greenery"],
    style: "modern",
    tileSize: 32,
    dimensions: { width: 1, height: 2 },
    placement: "floor",
    tilesetId: "decor-pack",
    tileId: 12,
  },
  {
    id: "retro.desk.small",
    name: "Retro writing desk",
    category: "furniture",
    subcategory: "desk",
    tags: ["desk"],
    style: "retro",
    tileSize: 16,
    dimensions: { width: 2, height: 1 },
    placement: "floor",
    tilesetId: "retro-pack",
    tileId: 3,
  },
] as const;

export const TILESETS = [
  { id: "office-core", name: "Office Core", version: "3", tileSize: 32 },
  { id: "decor-pack", name: "Decor Pack", version: "1", tileSize: 32 },
];
